version: '3.8'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_started

    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      ES_HOST_URL: "http://elasticsearch:9200"
      HAYSTACK_TELEMETRY_ENABLED: False

    env_file:
      - .env
    ports:
      - "8080:8080"

    healthcheck:
      test: [ "CMD", "curl", "-f", "-s", "http://backend:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3

    volumes:
      - /home/nikunj/models/:/models/

  frontend:
    build: ./frontend
    ports:
      - "8053:8053"
    depends_on:
      backend:
        condition: service_started
    environment:
      BACKEND_URL: "http://backend:8080"

  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.network.tcp.connect_timeout=180s"
      - "ES_INDEX_NUMBER_OF_SHARDS=1"
      - "ES_INDEX_NUMBER_OF_REPLICAS=1"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3




  migration:
    build:
      context: ./migration
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432

volumes:
  elasticsearch_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nikunj/PycharmProjects/DocAI/elasticsearch_data
  postgresql_data:
    driver: local