export const ROUTE = {
    ROOT: '/',
    AUTH: 'auth',
    LOGIN: 'login',
    FORGOT_PASSWORD: 'forgot-password',
    RESET_PASSWORD: 'reset-password',
    SEARCH: 'home',
    CHAT: 'chat',
    INDEX_LIST: 'brains',
    INDEX_ID: 'index-id',
    CHAT_ID: 'chat_uuid',
    BRAINS: 'brains',
    SET_USER_DETAILS: 'set-user-details',
    INVITE: 'invite',
    WILDCARD: '*',
};
